#!/bin/bash

declare -a portarr=("5611" "9090")

zipfiles=`git diff HEAD --name-only | grep -E '.zip' | sed -e 's/\.zip$//'`

# Check manual deployment in new namespace.

# Create variable for seperate domains using grep/sed -
# need this because of no passed domain vars between migrate-backup.
# Pass domains to dps and generate additional domains in yaml.

# Change secret creation in docs for domains.
# Use dps as a reference.

# Use extracted array to manipulate both cfg & local yamls' naming conventions -
# by removing the enviroment flag name - might do in migrate-backup.

# Iterate sync-waves for multiple domains for cfg, local, and routes yamls.

# Check add logic for multiple domain configmaps.
# Check add logic for kustomization.yaml - ensure names are correct.
# Check remove logic for GitOps DP multiple domain yamls.

# DEMO ----------------------------------------
# Changed DPS pods to 1 to show scaling up with GitOps.
# Point out sync-wave iteration.

for file in $zipfiles; do
  if [[ -f $file.zip ]]; then
    if [ -d "${file}" ] ; then
      rm -r $file
    fi

    echo "extracting resources from ${file}.zip"
    ./migrate-backup.sh $file.zip
    ./migrate-backup-dps.sh $file > ./$file/$file-output/$file-dps.yaml
    echo "./$file/$file-output/$file-dps.yaml created"
    ./migrate-backup-service.sh $file "${portarr[@]}" > ./$file/$file-output/$file-service.yaml
    echo "./$file/$file-output/$file-service.yaml created"
    for port in "${portarr[@]}"; do
      ./migrate-backup-route.sh $file "$port" > ./$file/$file-output/$file-"$port"-route.yaml
      echo "./$file/$file-output/$file-"$port"-route.yaml created"
    done;

    # Manipulate cfg files name if not doing in migrate-backup

    sed -i '' 's/[{}]//g' ./$file/$file-output/$file-service.yaml
    git add $file
  else
    if [ -d "${file}" ] ; then
      rm -r $file
      git rm -r $file
    fi
  fi
done

# For GitOps interaction with the multi-tenancy-gitops-apps repo
# Comment this section out if not using GitOps

yamlfiles=`git diff HEAD --name-only | grep -E '.yaml'`

cd ..

for file in $yamlfiles; do
  if [[ -f "./datapower-operator-scripts/${file}" ]]; then
    if [[ "$file" == *-dps* ]]; then
      array=($(echo "$file" | tr '/' '\n'))
      yes | cp -f "./datapower-operator-scripts/${file}" ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/datapower/
      echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/datapower/${array[1]} created"
      echo -e "- datapower/${array[1]}" >> ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/kustomization.yaml
    elif [[ "$file" == *-service* ]]; then
      array=($(echo "$file" | tr '/' '\n'))
      yes | cp -f "./datapower-operator-scripts/${file}" ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/service/
      echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/service/${array[1]} created"
      echo -e "- service/${array[1]}" >> ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/kustomization.yaml
    elif [[ "$file" == *-route* ]]; then
      array=($(echo "$file" | tr '/' '\n'))
      yes | cp -f "./datapower-operator-scripts/${file}" ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/route/
      echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/route/${array[1]} created"
      echo -e "- route/${array[1]}" >> ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/kustomization.yaml
    elif [[ "$file" == *default* ]]; then
      array=($(echo "$file" | tr '/' '\n'))
      yes | cp -f "./datapower-operator-scripts/${file}" "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/configmap/${array[0]}-${array[2]}"
      echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/configmap/${array[0]}-${array[2]} created"
      echo -e "- configmap/${array[0]}-${array[2]}" >> ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/kustomization.yaml
    fi
  else
    if [[ "$file" == *-dps* ]]; then
      array=($(echo "$file" | tr '/' '\n'))
      if [[ -f "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/datapower/${array[1]}" ]]; then
        rm "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/datapower/${array[1]}"
        echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/datapower/${array[1]} deleted"
        grep -v  "datapower/${array[1]}" \
        ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/kustomization.yaml > \
        temp && mv temp ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/kustomization.yaml
      fi
    elif [[ "$file" == *-service* ]]; then
      array=($(echo "$file" | tr '/' '\n'))
      if [[ -f "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/service/${array[1]}" ]]; then
        rm "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/service/${array[1]}"
        echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/service/${array[1]} deleted"
        grep -v  "service/${array[1]}" \
        ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/kustomization.yaml > \
        temp && mv temp ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/kustomization.yaml
      fi
    elif [[ "$file" == *-route* ]]; then
      array=($(echo "$file" | tr '/' '\n'))
      if [[ -f "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/route/${array[1]}" ]]; then
        rm "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/route/${array[1]}"
        echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/route/${array[1]} deleted"
        grep -v  "route/${array[1]}" \
        ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/kustomization.yaml > \
        temp && mv temp ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/kustomization.yaml
      fi
    elif [[ "$file" == *default* ]]; then
      array=($(echo "$file" | tr '/' '\n'))
      if [[ -f "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/configmap/${array[0]}-${array[2]}" ]]; then
        rm "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/configmap/${array[0]}-${array[2]}"
        echo "./multi-tenancy-gitops-apps/dp/environments/dev/datapower/configmap/${array[0]}-${array[2]} deleted"
        grep -v  "configmap/${array[0]}-${array[2]}" \
        ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/kustomization.yaml > \
        temp && mv temp ./multi-tenancy-gitops-apps/dp/environments/dev/datapower/kustomization.yaml
      fi
    fi 
  fi
done
