apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "350"
  name: marriott-demo-instance
spec:
  replicas: 1
  version: 10.0-cd
  license:
    accept: true
    use: nonproduction
    license: L-RJON-CCCP46
  users:
  - name: admin
    accessLevel: privileged
    passwordSecret: datapower-user
  domains:
    - name: default
      dpApp:
        config:
        - default-cfg
        local:
        - default-local
    - name: dev-marsha
      certs:
      - certType: usrcerts
        secret: dev-marsha-cert
      dpApp:
        config:
        - dev-marsha-cfg
        local:
        - dev-marsha-local
